project:
  type: website
  output-dir: docs 
  resources:
    - CNAME
    - attachments/**
  render:
    - "*qmd"
    - "!backup_pt_legacy/"
  

website:
  title: "Lidiany Cerqueira, PhD"
  google-analytics: "G-NTTVS2BF7B"
  site-url: "https://lidianycs.site"
  favicon: attachments/Logo.png
  cookie-consent: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: datasets.qmd
        text: Datasets  
      - href: publications.qmd
        text: Publications
      - href: outreach.qmd
        text: Outreach
      - href: teaching.qmd
        text: Teaching
      - href: service.qmd
        text: Service
      - href: attachments/cv.pdf
        text: CV
        target: _blank
    right:
      - text: "{{< ai google-scholar >}} <span class='visually-hidden'>Google Scholar</span>"
        href: https://scholar.google.com/citations?user=kxhHAW4AAAAJ
        target: _blank
      - text: "{{< ai orcid >}} <span class='visually-hidden'>ORCID</span>"
        href: http://orcid.org/0000-0002-4989-0986
        target: _blank
      - text: "{{< ai researchgate >}} <span class='visually-hidden'>ResearchGate</span>"
        href: https://www.researchgate.net/profile/Lidiany-Cerqueira?ev=hdr_xprf
        target: _blank
      - text: "<i class='bi bi-github'></i> <span class='visually-hidden'>GitHub</span>"
        href: https://github.com/lidianycs
        target: _blank
      - text: "<i class='bi bi-linkedin'></i> <span class='visually-hidden'>LinkedIn</span>"
        href: https://www.linkedin.com/in/lidianycs
        target: _blank
      - text: "{{< fa brands bluesky >}} <span class='visually-hidden'>Bluesky</span>"
        href: https://bsky.app/profile/lidianycs.bsky.social
        target: _blank
      - text: "<i class='bi bi-envelope'></i> <span class='visually-hidden'>Email</span>"
        href: "mailto:lidianycs@gmail.com"

  
  page-footer:
    left: "Made with ‚ù§Ô∏è‚Äçüî• using [Quarto](https://quarto.org/) ¬© 2026 Lidiany Cerqueira"
    right:
      - icon: github
        href: https://github.com/lidianycs
        aria-label: "GitHub"
      - icon: linkedin
        href: https://linkedin.com/in/lidianycs
        aria-label: "LinkedIn"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true

lang: en

cookie-consent:
  type: express  
  style: simple
  palette: light